name: Preview API Worker

on:
  pull_request:
    paths:
      - "apps/api-worker/**"
      - "packages/schema/**"
  push:
    branches:
      - "feature/**"

jobs:
  deploy-preview-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22

      - name: Install deps
        run: npm install

      - name: Deploy API worker (preview)
        working-directory: apps/api-worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx wrangler deploy --env preview
