name: Preview Web Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336abf0e0f52c777ae4f975e966d0

      - name: Setup Node
        uses: actions/setup-node@60edb5dd7ba3c0c2c5e0df3e00d8c3f1e5f1b8ac
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Web App
        run: pnpm --filter "./apps/web" build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@e4e6f7e75eb3dda82db28134c66da2db78df12d4
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: gs-web
          directory: apps/web/dist
